### ISSUE TITLE
How do you actually set up this with https?

### ISSUE THREAD

**Issue by Fluffacorn** [awesometic/docker-h5ai#23]
Title explains itself, I can't find a way to set up certbot properly. Is there any tutorial for how I'd go about doing it?

**Comment by awesometic** [comment]
Hello,

You can enable SSL using a reverse proxy server.
In my case, I use Linuxserver's SWAG project: https://docs.linuxserver.io/general/swag

The Nginx config this project has is ready for use Let's encrypt certbot.
Since there are many related tutorials about SWAG on Google, you can easily build your server. :)

**Comment by Fluffacorn** [comment]
I tried that, but I got a `Bind for 0.0.0.0:80 failed: port is already allocated` error. I'm not too sure how it's supposed to work.

What I tried: ran docker-h5ai in one container, set up swag in another container. When trying to run swag, it throws me that error.

**Comment by awesometic** [comment]
Maybe there's another process that uses the 80 port. You should use the 80 port to Swag first, then make it proxies the other web programs inside by domain or something.

**Comment by Fluffacorn** [comment]
the other process that uses the 80 port is h5ai docker, though. I'm lost, sorry if this seems dumb but I'm unsure as to how to make this work. I also tried manually installing certbot in the docker container via docker exec, but I couldn't get that to work.

**Comment by awesometic** [comment]
If you set an internal network for h5ai and Swag, you don't need to open 80 port for h5ai. Setting reverse proxy (Swag) which means making all the incoming requests from the Internet through the proxy server. Swag, the reverse proxy server, will determine the proper destination by its configs.

This can be looked seems complex, but you're getting familiar with the Docker use.. :)

**Comment by awesometic** [comment]
I will close this issue because it is not directly related to this project. 😃

**Comment by Fluffacorn** [comment]
**_final_** question, since I'm a bit confused.

the docker command used to start this includes:
 `docker run -d --name=h5ai \
-p 80:80 \`

You said I don't need to open the 80 port for h5ai, but how am I supposed to do that when it's in the command?

**Comment by awesometic** [comment]
Sorry for the late reply,

The example assumes that we're not using any proxy system. If you don't need HTTPS, you can open 80 port for the Internet.

Otherwise, if you want to use HTTPS then you will need a Docker network to connect the reverse proxy server and h5ai, then the reverse proxy server can send packets to h5ai in the internal Docker network.

So, even if you have multiple web services that all needs 80 or 443 ports, you can make only one service open 80, 443 ports and you don't need to care about the port forwarding of the web services. That one opens the ports will surely be the reverse proxy server.
