### ISSUE TITLE
Builds for arm64

### ISSUE THREAD

**Issue by b-ggs** [awesometic/docker-h5ai#4]
First of all, thank you for creating this repo! I have zero clue on how to work with PHP and was having a tough time trying to build a Docker image for h5ai!

I have been building arm64 images of your repo because I wanted to run them off of my Raspberry Pi. Building arm64 works out the box without any changes to your code. https://github.com/b-ggs/dockerfiles/runs/1914884700?check_suite_focus=true

I was wondering if you're interested in supporting arm64 or possible other architectures like arm32v7.

I can contribute but I don't think there's a fully supported way to do it with Docker cloud. I have mine set up with GitHub Actions. https://github.com/b-ggs/dockerfiles/blob/9b15759b2e6596e9ed7cc9aa713988047d63d7f8/.github/workflows/buildx.yml#L46

**Comment by awesometic** [comment]
Hi, Thanks for the suggestion!

It is a great idea that supporting ARM architectures since many powerful ARM-based computers pouring out today, like Raspberry Pi and Odroid, and Apple Silicon.

In fact, I have no experience serving multiple architectures in the same Docker image using Docker Hub.
But fortunately, I just found that someone does this thing by using Github Actions just like you.

So, now there're at least two references to use Github Actions to publish a Docker image to Docker Hub. :)
I think I can support arm64/arm32v7 as well as x86 by referring to those great references.

It might take a few days because I'm new to using Github Actions. :)

**Comment by binge8** [comment]
https://hub.docker.com/r/bin20088/h5ai

**Comment by awesometic** [comment]
> https://hub.docker.com/r/bin20088/h5ai

Wow, I didn't know that. Thank you!
I hope I can do like you onto my repository. I will study your Workflow too, and I will patch my repository within a few days. 😃
